spring:
  application:
    name: main-service

server:
  port: 8094

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://discovery:8091/eureka/

elasticsearch:
  hostname: elastic
  port: 9200