spring:
  application:
    name: middleware-service

server:
  port: 8093

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://discovery:8091/eureka/